
# 1. We define the name.
name: Android Release

# 2. We define the when we have to start the action like: on push or pull_request
on:

  # 3. We are defining the action on push.
  push:
    branches: ['master']

  #4. Event to trigger workflow.
  workflow_dispatch:

#5. Defining the jobs.like: what to when workflow executes
# for ex: build apk or ipa on push the code.
jobs:
  #6. here we are making a build
  build:
    #7. we are defining the machine to run the work-flow.
    runs-on: ubuntu-latest
    #8.
    steps:
      # 9
      - uses: actions/checkout@v3
      # 10
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      # 11
      - uses: subosito/flutter-action@v2
        with:
          # 12
          flutter-version: "3.10.3"
          channel: 'stable'
          cache: true
      # 13
      - name: Get dependencies
        run: flutter pub get
      # 14
      - name: Start release build
        run: flutter build appbundle
